### ISSUE TITLE
end of line in @btime

### ISSUE THREAD

**Issue by iwelch** [JuliaCI/BenchmarkTools.jl#104]
it would be nice if you added an option to remove the end-of-line in the `@btime` output, so that it can be embedded in the middle of a line.  (or stream so that one can postprocess it?)

**Comment by jrevels** [comment]
I think the intent with `@btime` was to mirror `@time` exactly, which also adds a newline in the printed output. Note that `@btime` also returns the given value, which one can use however they wish. 

If one wishes to do serious benchmark post-processing, though, I suggest they use the BenchmarkTools methods that return all benchmark data (`@benchmarkable`/`run`, or `@benchmark`)  rather than the `@btime` convenience macro, which is generally only meant to be used interactively, e.g. at the REPL.

Closing, but feel free to discuss. If there are serious objections, we could reopen the issue.
