### ISSUE TITLE
Installation time on OSX / dependencies

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaCI/BenchmarkTools.jl#53]
Installing this on OS X takes about 10 minutes, downloading and compiling things, even installing python. It also breaks my Gtk.jl installation (it replaces the libraries with other versions).

This seems a bit excessive for such a simple package, why does it need so much binary dependencies? I'm not sure where the issue is coming from, I guess from JLD.

**Comment by jrevels** [comment]
As you pointed out, this is a consequence of depending on JLD.  We unfortunately need to depend on JLD for `BenchmarkTools.save`/`BenchmarkTools.load` (used for cross-version benchmarking). 

I guess we could factor out the serialization compatibility layer into a separate package, so that BenchmarkTools itself doesn't need to depend on JLD.

**Comment by cstjean** [comment]
FWIW, I've had a good experience with JLD2.jl so far.

**Comment by jrevels** [comment]
fixed by #79
