### ISSUE TITLE
Add docstring for @benchmark

### ISSUE THREAD

**Issue by dpsanders** [JuliaCI/BenchmarkTools.jl#63]
help?> @benchmark
  No documentation found.

**Comment by thchr** [comment]
This is unfortunately also the "dead-end" point for the doc-strings of `@btime`, `@belapsed`, and `@ballocated`, e.g.:

```jl
help?> @btime
  @btime expression [other parameters...]

  (...)

  Unlike @time, it uses the @benchmark macro, and accepts all of the same additional
  parameters as @benchmark. The printed time is the minimum elapsed time measured
  during the benchmark.

help?> @benchmark
  No documentation found.
```

I guess the relevant information is in [manual.md](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#benchmark-parameters); a question is whether some version of that could be copied more-or-less wholesale to the docstring.

**Comment by FedericoStra** [comment]
The reason is that the docstring of `@benchmark` ([link](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/src/execution.jl#L324-L382)) is a raw string (`raw""" ... """`), hence ([according to the manual](https://docs.julialang.org/en/v1/manual/documentation/#Advanced-Usage)) `@doc` is required. I've just submitted a PR #203 that fixes this.

**Comment by FedericoStra** [comment]
There should probably be a linter that detects
```julia
raw"""
...
"""
function ...
    ...
end
```
and warns about the missing `@doc`. Or even better, it should just work...
