### ISSUE TITLE
broken on master:  invalid syntax

### ISSUE THREAD

**Issue by musm** [JuliaCI/BenchmarkTools.jl#69]
```julia
julia> f() =0
f (generic function with 1 method)

julia> @btime f()
ERROR: syntax: invalid syntax (escape (call (outerref f)))
Stacktrace:
 [1] generate_benchmark_definition(::Module, ::Array{Symbol,1}, ::Array{Any,1}, ::Expr, ::Void, ::Void, ::BenchmarkTools.Parameters) at C:\Users\Mus\.julia\v0.7\BenchmarkTools\src\execution.jl:289

```

**Comment by giordano** [comment]
I've been seeing this error for a while (more than a week), I was surprised that no one else reported it, so I thought at first that I had something broken on my machine.

I didn't git-bisect Julia to see when this got broken, I just tried two commits:
* on https://github.com/JuliaLang/julia/commit/952dc93489213327147c7d7d14182a81eda35835 `BenchmarkTools` still works
* on https://github.com/JuliaLang/julia/commit/8d85aa47e8dc27f23daf09f0343a7868931ef9ef it's broken

Thus I suspect this is another example of breakage produced by https://github.com/JuliaLang/julia/pull/22985

**Comment by jrevels** [comment]
I'll try to get around to fixing this this week, since it seems to be affecting a lot of people.

In the meantime, if somebody wants to take a crack at this before I get to it, I recommend [investigating the macro scoping bugs pointed out a long time ago](https://github.com/JuliaCI/BenchmarkTools.jl/pull/61#discussion_r121386643), keeping in mind that we need to preserve the behavior I mentioned [here](https://github.com/JuliaCI/BenchmarkTools.jl/issues/65#issuecomment-313926098).
